# values.yaml includes qa settings

virtualService:
  create: true
  hosts:
    - qa.twplatformlabs.org
  gateways:
    - istio-system/qa-twplatformlabs-org-gateway
  matchUrl: /v1/hello

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  utilizationMethod: memory
  targetUtilizationPercentage: 80

podDisruptionBudget: 
  create: true
  maxUnavailable: 1
